export default {
  Date: "ASSIGNMENT_DATE",
  Section: "PLSS_SECTION",
  Subdivision: "SUBDIVISION",
  COS: "COS",
  Block: "BLOCK",
  Comments: "COMMENTS",
  ADDRESS_NUMBER: "ADDRESS_NUMBER",
  STREET_NAME: ["DIRPRE", "ROADNAME", "ROADTYPE", "DIRSUF"],
  Contact_Individual: "CONTACT_INDIVIDUAL",
  Encroachment_Permit_Required: "",
  Contact_Telephone: "CONTACT_PHONE",
  Township_Range: "TOWNSHIP_RANGE",
  Atlas_Page: "",
  Lot_Tract: "LOT_TRACT",
  Deed_Ref: "DEED_REF",
  ArcMap_Updated: "",
  Access_Updated: "",
  Type_of_Structure: "STRUCTURE_TYPE",
  GIS_Signature: "",
  Property_Agent_Signature: "",
  PIF: "PIRF_NUMBER",
  Unit: "Unit",
};
